--- 
env: 
  ES_PROTOCOL: http
  ES_HOST: localhost
  ES_PORT: 9200
  ES_USER: ~
  ES_PASS: ~
  ES_SSL_CERT: ~
  ES_SSL_KEY: ~
  KB_HOST: localhost
  KB_PORT: 5601
  KB_INDEX: ~
  HTTP_PORT: 8080
params: 
  required: 
    - log.test_info
    - log.env_tester
    - log.team
    - log.browser
    - log.env_target
  defaults: 
    baseline: 
      days: 7
      perc: 75
      padding: 1.2
    flags: 
      assertBaseline: true
      debug: false
      esCreate: false
      esTrace: false
      passOnFailedAssert: false