language: node_js

cache:  
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '9'
  - '8'

before_install:
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - npm run test

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
